Proposal commits
BeeTech-global/bee-stylish pull request #1
Opened 2017-09-18 20:27 UTC by evansantos

Proposta contendo um conteúdo do styleguide de commits para ser agregado ao bee-stylish

2017-09-27 14:12 UTC, guilhermegm requested changes

2017-09-27 14:12 UTC, guilhermegm commented on commits/README.md
> +- Não terminar um título com ponto
Título ou assunto?

2017-09-27 14:12 UTC, guilhermegm commented on commits/README.md
> +- Limitar o corpo da mensagem em 80 caracteres
limitar o corpo do commit...?

2017-09-27 14:12 UTC, guilhermegm commented on commits/README.md
> +<rodapé>
Teve explicação do pq rodapé?

2017-09-27 14:12 UTC, guilhermegm commented on commits/README.md
> +Adiciona o get aos serviços da api para garantir que a listagem, seja carregada de forma dinâmica e atualizada pela api
Qual vai ser o idioma padrão, faz sentido?

O corpo e rodapé são sempre obrigatórios?

2017-10-02 22:22 UTC, airroom approved these changes
Acho que tá bunitim O.o

2017-10-02 23:01 UTC, guilhermegm approved these changes

2017-10-02 23:02 UTC, merged