Styleguide infra
BeeTech-global/bee-stylish pull request #10
Opened 2017-10-14 18:08 UTC by mrprompt

2017-10-14 18:39 UTC, airroom commented on infra/README.md
> +"Com grandes poderes requerem grandes responsabilidaes", dizia o sábio Tio Joe, é verdade. Como você pode ver no exemplo acima, a configuração do Pipelines fica totalmente disponível para os desenvol
Tio Ben eim?

2017-10-14 18:39 UTC, airroom commented on infra/README.md
> +## Segundo passo: Doutrinando o time
<p align="center"><img src="http://4.bp.blogspot.com/-EWDyCZWPj8I/VngLc_V4hoI/AAAAAAAABjc/PtNIEVqyPMU/s1600/Apollo.jpg"></p>

2017-10-14 18:40 UTC, mrprompt commented on infra/README.md
> +"Com grandes poderes requerem grandes responsabilidaes", dizia o sábio Tio Joe, é verdade. Como você pode ver no exemplo acima, a configuração do Pipelines fica totalmente disponível para os desenvol
https://pt.wikipedia.org/wiki/Ben_Parker 💃

2017-10-14 18:41 UTC, mrprompt commented on infra/README.md
> +"Com grandes poderes requerem grandes responsabilidaes", dizia o sábio Tio Joe, é verdade. Como você pode ver no exemplo acima, a configuração do Pipelines fica totalmente disponível para os desenvol
ahahahaha agor que vi que deixei Joe

2017-10-14 18:43 UTC, airroom commented on infra/README.md
> +Para termos essa flexibilidade na infra, sem prejudicar ou onerar ninguém, optamos por utilizar a [Heroku](https://www.heroku.com) - se você não conhece a Heroku, deveria - como [PaaS](https://pt.wik
Ao invés do deveria, poderia ser um "ta aí a desculpa perfeita para aprender" hihi

2017-10-14 18:43 UTC, airroom commented on infra/README.md
> +"Com grandes poderes requerem grandes responsabilidaes", dizia o sábio Tio Joe, é verdade. Como você pode ver no exemplo acima, a configuração do Pipelines fica totalmente disponível para os desenvol
ASUEHSAUEHSA

2017-10-15 02:42 UTC, airroom commented on infra/README.md
> +Não meu caro, o que o _cara da infra_ te diria? Que isso precisa rodar em um ambiente separado, correto? Mas, então porquê não automatizar isso? Porque você mesmo não sobe seu ambiente para testar su
"por que não automatizar"

2017-10-15 13:54 UTC, mrprompt commented on infra/README.md
> +Não meu caro, o que o _cara da infra_ te diria? Que isso precisa rodar em um ambiente separado, correto? Mas, então porquê não automatizar isso? Porque você mesmo não sobe seu ambiente para testar su
fixed!

2017-10-15 20:18 UTC, airroom approved these changes
BOUUUUA

2017-10-16 12:46 UTC, evansantos commented on infra/README.md
> +"Com grandes poderes requerem grandes responsabilidaes", dizia o sábio [Tio Ben](https://pt.wikipedia.org/wiki/Ben_Parker), é verdade. Como você pode ver no exemplo acima, a configuração do Pipelines
"Com grandes poderes requerem grandes responsabilidades"

2017-10-16 12:55 UTC, evansantos requested changes

2017-10-16 12:55 UTC, evansantos commented on infra/README.md
> +Caso precise rodar alguma tarefa a antes ou depois do build, mas apenas na Heroku, temos a opção de criar em **scripts** os gatilhoes pré-configurados da Heroku: pre-build ou post-build. Na [document
"gatilhões"

2017-10-16 12:55 UTC, evansantos commented on infra/README.md
> +Sim, é esta a infra matadora, sem trabalho, sem estresse e linda de ver funcionando.
"Sim, esta é a infra matadora"

2017-10-16 12:55 UTC, evansantos commented on infra/README.md
> +Por utilizar Docker, já ganhamos máxima liberdade na criação do ambiente de testes e garante total compatilidade entre os ambientes, já que podemos utilizar o mesmo container em todos.
"já ganhamos máxima liberdade na criação do ambiente de testes e garante total compatibilidade entre os ambientes"

2017-10-16 16:41 UTC, evansantos approved these changes

2017-10-16 16:41 UTC, evansantos commented
LGTM 👍

2017-10-16 19:06 UTC, guilhermegm approved these changes

2017-10-20 13:00 UTC, airroom commented
CADÊ CADÊ CADÊ? :(

2017-10-21 02:08 UTC, mrprompt commented
ta difícil :(

2017-10-24 03:38 UTC, mrprompt commented
approved!!!! \o/

2017-10-24 03:39 UTC, merged