adicionando doc de trabalho remoto
BeeTech-global/bee-stylish pull request #12
Opened 2018-04-27 18:39 UTC by edisonrocha

Adicionado guia para o trabalho remoto feito em conjunto com @mrprompt 
:)

2018-04-27 18:41 UTC, JrFarias commented
Demais galera hahahah

2018-04-27 18:46 UTC, lucasdaiki approved these changes
BOA CARAJOOO

2018-04-27 19:03 UTC, IcaroBichir approved these changes

2018-04-27 19:03 UTC, airroom commented
O título só tem que terminar com um aumentativo boladão o/

2018-04-27 20:25 UTC, mrprompt requested changes
Parece que no final do texto um pedaço foi comido, pq a frase ficou incompleta na parte de dicas.

2018-05-10 13:25 UTC, evansantos commented on trabalho-remoto/README.md
> +* Tenha horários pré-definidos para o trabalho, almoço e descanso - Por vezes o trabalhador remoto se perde no tempo e
concordo só com essa parte que o @mrprompt falou :)

2018-05-10 13:32 UTC, IcaroBichir commented on trabalho-remoto/README.md
> +* Tenha horários pré-definidos para o trabalho, almoço e descanso - Por vezes o trabalhador remoto se perde no tempo e
"só com essa parte"? kkkkk

2018-05-10 13:54 UTC, IcaroBichir commented on trabalho-remoto/README.md
> +    * Slack (sério, usemos o whatsapp, telegram, skype, google talk, msn, icq e irq somente para conversas pessoais e memes).
Esse sério é real demais! Pra quem está em casa é muito treta pra conseguir acompanhar as conversas em lugares diferentes.

2018-05-10 14:17 UTC, marciowmc commented on trabalho-remoto/README.md
> +O ideal é que a comunicação seja centralizada em ferramentas corporativas disponibilizadas pela empresa. Isso evita a dispersão de informação e confusões do tipo "Qual é o canal da semanal?" além de
Sugestão de ortografia...

além de nos ajudar a manter um histórico consolidado do que já foi discutido. Resumindo: Whatsapp é bom pra mandar memes e marcar brejas. Papo de trampo é no Slack!

Whatsapp acho que também pode ser usado para coisas mais emergenciais, dado que existem planos de internet que nem cobram isso ( indo bem além aqui )

2018-05-10 14:18 UTC, mrprompt commented on trabalho-remoto/README.md
> +O ideal é que a comunicação seja centralizada em ferramentas corporativas disponibilizadas pela empresa. Isso evita a dispersão de informação e confusões do tipo "Qual é o canal da semanal?" além de
D-u-v-i-d-o tu mandar um commit com isso.

2018-05-11 21:15 UTC, evansantos approved these changes

2018-05-12 15:22 UTC, merged