feat(repository-pattern): Add repository pattern documentation
BeeTech-global/bee-stylish pull request #14
Opened 2019-12-02 19:24 UTC by MarcosRava

2019-12-02 19:30 UTC, santanagbr approved these changes

2019-12-02 19:36 UTC, emersonjds approved these changes

2019-12-03 01:04 UTC, marciowmc reviewed
@MarcosRava poderiamos adicionar uma estrutura que mostra o encadeamento dessas camadas pra deixar ainda mais claro.

https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.slideshare.net%2Fandrewjutton%2Fmvc-website-pattern-the-controller-task-repository-command-pattern&psig=AOvVaw2N6vVQw_YhvO7xUTJhCEAv&ust=1575421349228000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCLjyo5CkmOYCFQAAAAAdAAAAABAP

2019-12-03 11:56 UTC, felipecodes approved these changes

2019-12-03 13:41 UTC, williansabiao requested changes

2019-12-03 13:41 UTC, williansabiao commented on repository-pattern/README.md
> +    return result .id;
Deveria ser `result.id` sem espaço certo? =D

2019-12-03 13:41 UTC, williansabiao commented on repository-pattern/README.md
> +        uri: 'https://api.com/v1customers' ,
Espaço a mais antes da vírgula.

2019-12-03 14:02 UTC, richardpassos01 approved these changes

2019-12-03 14:09 UTC, MarcosRava commented
> @MarcosRava poderiamos adicionar uma estrutura que mostra o encadeamento dessas camadas pra deixar ainda mais claro.
> 
> https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.slideshare.net%2Fandrewjutton%2Fmvc-website-pattern-the-controller-task-repository-command-pattern&psig=AOvVaw2N6vVQw_YhvO7xUTJhCEAv&ust=1575421349228000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCLjyo5CkmOYCFQAAAAAdAAAAABAP

Não entendi @marciowmc

2019-12-03 15:40 UTC, williansabiao approved these changes

2019-12-04 14:40 UTC, merged