feat(tests): Add tests documentation
BeeTech-global/bee-stylish pull request #17
Opened 2019-12-11 16:11 UTC by MarcosRava

2019-12-11 17:50 UTC, santanagbr approved these changes

2019-12-11 19:57 UTC, darthtai approved these changes

2019-12-11 20:42 UTC, ViniciusTavares requested changes

2019-12-11 20:42 UTC, ViniciusTavares commented on tests/README.md
> +## Coverage
Seria interessante fazer um topico sobre os pre hook tambem, e tambem acho que seria interessante oficializar o block de commit / pr baseado numa score de coverage

2019-12-11 20:42 UTC, ViniciusTavares commented on tests/README.md
> +  const result = await createCustomer(customer);
Nesse exemplo, adicionem uma linha que verifica se o createCustomer foi de fato chamado com o objeto customer, e tambem seria interessante adicionar o calledOnlyOnce() ou algo parecido, para dar um exemplo mais completo de possiveis/recomendadas validacoes no teste unitario

2019-12-11 22:22 UTC, ViniciusTavares approved these changes

2019-12-11 22:22 UTC, ViniciusTavares commented on tests/README.md
> +repositoryMock.expects('findAll').once().withArgs('users')
Agora vi que voces ja validam os args aqui. Desconsiderem o comentario sobre isso acima haha

2019-12-12 13:43 UTC, MarcosRava commented on tests/README.md
> +## Coverage
É interessante os hooks, não consigo imaginar como encaixaria isso no tópico de testes, acho que poderia ser em algo sobre git, tem alguma ideia de como fazer isso?

Sobre a % do coverage, é uma política interna, não o quanto faz sentido deixar em um documento publico, mas dá para citar a possibilidade de fazer isso

2019-12-12 13:46 UTC, MarcosRava commented on tests/README.md
> +  const result = await createCustomer(customer);
Esse não é um teste unitário Vini, é o teste de integração, onde o foco é verificar se as duas peças estão funcionando bem integradas

2019-12-12 13:56 UTC, MarcosRava commented on tests/README.md
> +  const result = await createCustomer(customer);
adicionei a linha 

> Pode ser usado como métrica para aceitação mínima de cobertura em um projeto e ter a validação a cada pull request com uma ferramenta de CI por exemplo

2019-12-17 19:38 UTC, henriquesgnc approved these changes

2019-12-17 19:38 UTC, merged